--------------------------------------------------------
-- Archivo creado  - sábado-noviembre-26-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CLIENTES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."CLIENTES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CLIENTES_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."CLIENTES_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CONTROL_SERVICIO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."CONTROL_SERVICIO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CONTROL_SERVICIO_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."CONTROL_SERVICIO_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 161 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CONTROL_SERVICIO_SEQ2
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."CONTROL_SERVICIO_SEQ2"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_CUST_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."DEMO_CUST_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_ORDER_ITEMS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."DEMO_ORDER_ITEMS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_ORD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."DEMO_ORD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_PROD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."DEMO_PROD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_USERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."DEMO_USERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EMPRESAS_CLIENTELA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."EMPRESAS_CLIENTELA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EMPRESAS_CLIENTELA_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."EMPRESAS_CLIENTELA_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 241 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EMPRESAS_CLIENTE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."EMPRESAS_CLIENTE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PROYECTO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."PROYECTO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PROYECTO_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."PROYECTO_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SERVICIOS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."SERVICIOS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SERVICIOS_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."SERVICIOS_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TRABAJADORES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."TRABAJADORES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USER_SISTEMA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."USER_SISTEMA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USER_SISTEMA_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."USER_SISTEMA_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USUARIOS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."USUARIOS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USUARIOS_SISTEMA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."USUARIOS_SISTEMA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USUARIOS_SISTEMA_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."USUARIOS_SISTEMA_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USUARIOS_SISTEMA_SEQ2
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."USUARIOS_SISTEMA_SEQ2"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CLIENTES
--------------------------------------------------------

  CREATE TABLE "PRUEBA"."CLIENTES" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"DIRECCION" VARCHAR2(50 BYTE), 
	"NIT" VARCHAR2(10 BYTE), 
	"TELEFONO" VARCHAR2(30 BYTE), 
	"TIPO_FK" NUMBER, 
	"OBSERVACION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CONTROL_SERVICIO
--------------------------------------------------------

  CREATE TABLE "PRUEBA"."CONTROL_SERVICIO" 
   (	"ID" NUMBER, 
	"EMPRESA_CLIENTE" VARCHAR2(150 BYTE), 
	"RESPONSABLE_EMPRESA_CLIENTE" VARCHAR2(150 BYTE), 
	"PROYECTO" VARCHAR2(150 BYTE), 
	"SERVICIO" VARCHAR2(150 BYTE), 
	"ENCARGADO_PRESTAR_SERVICIO" VARCHAR2(150 BYTE), 
	"FECHA_INICIO" DATE, 
	"HORA_INICIO" VARCHAR2(20 BYTE), 
	"FECHA_FIN" DATE, 
	"HORA_FIN" VARCHAR2(20 BYTE), 
	"DURACION_SERVICIO" NUMBER, 
	"DESCRIPCION" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPRESAS_CLIENTE
--------------------------------------------------------

  CREATE TABLE "PRUEBA"."EMPRESAS_CLIENTE" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"DESCRIPCION" VARCHAR2(50 BYTE), 
	"DIRECCION" VARCHAR2(50 BYTE), 
	"PRESUPUESTO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPRESAS_CLIENTELA
--------------------------------------------------------

  CREATE TABLE "PRUEBA"."EMPRESAS_CLIENTELA" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"DESCRIPCION" VARCHAR2(155 BYTE), 
	"DIRECCION" VARCHAR2(155 BYTE), 
	"RESPONSABLE" VARCHAR2(155 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FECHAS
--------------------------------------------------------

  CREATE TABLE "PRUEBA"."FECHAS" 
   (	"FECHA" DATE, 
	"HORA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERFIL_PUESTO_DE_TRABAJO
--------------------------------------------------------

  CREATE TABLE "PRUEBA"."PERFIL_PUESTO_DE_TRABAJO" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"DESCRIPCION" VARCHAR2(100 BYTE), 
	"PUESTO_DE_TRABAJO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROYECTO
--------------------------------------------------------

  CREATE TABLE "PRUEBA"."PROYECTO" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"DESCRIPCION" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PUESTO_DE_TRABAJO
--------------------------------------------------------

  CREATE TABLE "PRUEBA"."PUESTO_DE_TRABAJO" 
   (	"ID" NUMBER, 
	"NOMBRE_PUESTO" VARCHAR2(50 BYTE), 
	"DESCRIPCION" VARCHAR2(155 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SERVICIOS
--------------------------------------------------------

  CREATE TABLE "PRUEBA"."SERVICIOS" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"DESCRIPCION" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRABAJADORES
--------------------------------------------------------

  CREATE TABLE "PRUEBA"."TRABAJADORES" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"TELEFONO" NUMBER, 
	"DIRECCION" VARCHAR2(255 BYTE), 
	"PUESTO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "PRUEBA"."USUARIOS" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"APELLIDO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIOS_SISTEMA
--------------------------------------------------------

  CREATE TABLE "PRUEBA"."USUARIOS_SISTEMA" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(30 BYTE), 
	"TIPO_USUARIO" VARCHAR2(20 BYTE), 
	"TIPO_USUARIO_NUM" NUMBER, 
	"ESTADO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into PRUEBA.CLIENTES
SET DEFINE OFF;
Insert into PRUEBA.CLIENTES (ID,NOMBRE,DIRECCION,NIT,TELEFONO,TIPO_FK,OBSERVACION) values ('1','Tripa Seca','Retalhuleu','12345','56430094','1','Es marica');
Insert into PRUEBA.CLIENTES (ID,NOMBRE,DIRECCION,NIT,TELEFONO,TIPO_FK,OBSERVACION) values ('2','Loro','Quetzaltenango','99999','87879','4','Esta enfermo');
Insert into PRUEBA.CLIENTES (ID,NOMBRE,DIRECCION,NIT,TELEFONO,TIPO_FK,OBSERVACION) values ('3','Servilleta','Cuyotenango','88888','0987655','3','Hijo del DBA');
Insert into PRUEBA.CLIENTES (ID,NOMBRE,DIRECCION,NIT,TELEFONO,TIPO_FK,OBSERVACION) values ('4','Mama Osa','Sacapulas','77777','12321','2','Ella es una mamaosa');
Insert into PRUEBA.CLIENTES (ID,NOMBRE,DIRECCION,NIT,TELEFONO,TIPO_FK,OBSERVACION) values ('5','Chash Firulais','USA','66666','345322','1','JAVASCRIPT SENNIOR');
Insert into PRUEBA.CLIENTES (ID,NOMBRE,DIRECCION,NIT,TELEFONO,TIPO_FK,OBSERVACION) values ('6','Papa porky','Guatemala','909876','66666','5','DBA');
Insert into PRUEBA.CLIENTES (ID,NOMBRE,DIRECCION,NIT,TELEFONO,TIPO_FK,OBSERVACION) values ('7','Gonzo','San Marcos','76567','043567','4','ccccccc');
Insert into PRUEBA.CLIENTES (ID,NOMBRE,DIRECCION,NIT,TELEFONO,TIPO_FK,OBSERVACION) values ('8','Elsa Capuntas','Sampololote','444444','343234','2','bbbbbb');
Insert into PRUEBA.CLIENTES (ID,NOMBRE,DIRECCION,NIT,TELEFONO,TIPO_FK,OBSERVACION) values ('9','El negro Darias','Mazatenango','33333','34521','1','jjjjjjj');
Insert into PRUEBA.CLIENTES (ID,NOMBRE,DIRECCION,NIT,TELEFONO,TIPO_FK,OBSERVACION) values ('10','Elver galarga','Retalhuleu','2222','09876','3','kkkkkkk');
Insert into PRUEBA.CLIENTES (ID,NOMBRE,DIRECCION,NIT,TELEFONO,TIPO_FK,OBSERVACION) values ('11','Porky','Zacapa','11111','56876','5','prueba');
REM INSERTING into PRUEBA.CONTROL_SERVICIO
SET DEFINE OFF;
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('106','probando---','probando----','probando','probando','probando',to_date('12/11/12','DD/MM/RR'),'01:12',to_date('12/11/12','DD/MM/RR'),'01:12','1','probando');
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('104','probando---','probando----','probando','probando','probando',to_date('12/11/12','DD/MM/RR'),'01:12',to_date('12/11/12','DD/MM/RR'),'01:12','1','probando');
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('105','probando---','probando----','probando','probando','probando',to_date('12/11/12','DD/MM/RR'),'01:12',to_date('12/11/12','DD/MM/RR'),'01:12','1','probando');
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('107','probando---','probando----','probando','probando','probando',to_date('12/11/12','DD/MM/RR'),'01:12',to_date('12/11/12','DD/MM/RR'),'01:12','1','probando');
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('108','probando---','probando----','probando','probando','probando',to_date('12/11/12','DD/MM/RR'),'01:12',to_date('12/11/12','DD/MM/RR'),'01:12','1','probando');
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('109','probando---','probando----','probando','probando','probando',to_date('12/11/12','DD/MM/RR'),'01:12',to_date('12/11/12','DD/MM/RR'),'01:12','1','probando');
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('141','Pollo Pinulito','Pepa la Cerdita PIG','system','Mantenimiento al sistema','Emanuel Juarez',to_date('03/04/15','DD/MM/RR'),'15:00',to_date('29/11/16','DD/MM/RR'),'11:03','3','PRUEBAAAAAAAAAAAAAA');
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('142','Masesa','David Rojas','Actualizar el Developer Express','Servicio de Prueba','Esteban Leal',to_date('01/02/15','DD/MM/RR'),'22:59',to_date('28/11/17','DD/MM/RR'),'01:00','3','Actualizacion');
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('143','Shadai','Tomy y Pichay','Instalar nueva Red','Instalar nueva Red','Gabriel Loba',to_date('31/12/16','DD/MM/RR'),'00:01',to_date('31/01/17','DD/MM/RR'),'23:59','3','verificacion');
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('144','Honda','Micho rizo','Cambio Fibra Optica','Dar soporte a Clientes nuevos','Esteban Leal',to_date('30/11/16','DD/MM/RR'),'22:58',to_date('30/11/21','DD/MM/RR'),'22:59','1','soporte');
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('145','Ingenio el Pilar','Ronald Gramajo','Proyecto DB','proyecto Vegeta','Julio Garcia',to_date('27/12/15','DD/MM/RR'),'21:58',to_date('31/12/16','DD/MM/RR'),'01:03','6','proyecto de base de datos');
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('146','Cinepolis','Jhony Bravo','Instalar nueva Red','Instalar nueva Red','Gabriel Loba',to_date('30/12/14','DD/MM/RR'),'22:59',to_date('31/12/16','DD/MM/RR'),'23:59','4','PRUEBA');
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('75','probando','probando','probando','probando','probando',to_date('12/11/12','DD/MM/RR'),'01:12',to_date('12/11/12','DD/MM/RR'),'01:12','1','probando');
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('119','probando---','probando----','probando','probando','probando',to_date('12/11/12','DD/MM/RR'),'01:12',to_date('12/11/12','DD/MM/RR'),'01:12','1','probando');
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('117','probando---','probando----','probando','probando','probando',to_date('12/11/12','DD/MM/RR'),'01:12',to_date('12/11/12','DD/MM/RR'),'01:12','1','probando');
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('118','probando---','probando----','probando','probando','probando',to_date('12/11/12','DD/MM/RR'),'01:12',to_date('12/11/12','DD/MM/RR'),'01:12','1','probando');
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('120','probando---','probando----','probando','probando','probando',to_date('12/11/12','DD/MM/RR'),'01:12',to_date('12/11/12','DD/MM/RR'),'01:12','1','probando');
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('121','probando---','probando----','probando','probando','probando',to_date('12/11/12','DD/MM/RR'),'01:12',to_date('12/11/12','DD/MM/RR'),'01:12','1','probando');
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('122','probando---','probando----','probando','probando','probando',to_date('12/11/12','DD/MM/RR'),'01:12',to_date('12/11/12','DD/MM/RR'),'01:12','1','probando');
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('123','probando---','probando----','probando','probando','probando',to_date('12/11/12','DD/MM/RR'),'01:12',to_date('12/11/12','DD/MM/RR'),'01:12','1','probando');
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('124','probando---','probando----','probando','probando','probando',to_date('12/11/12','DD/MM/RR'),'01:12',to_date('12/11/12','DD/MM/RR'),'01:12','1','probando');
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('125','probando---','probando----','probando','probando','probando',to_date('12/11/12','DD/MM/RR'),'01:12',to_date('12/11/12','DD/MM/RR'),'01:12','1','probando');
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('126','probando---','probando----','probando','probando','probando',to_date('12/11/12','DD/MM/RR'),'01:12',to_date('12/11/12','DD/MM/RR'),'01:12','1','probando');
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('127','probando---','probando----','probando','probando','probando',to_date('12/11/12','DD/MM/RR'),'01:12',to_date('12/11/12','DD/MM/RR'),'01:12','1','probando');
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('147','Transportes Ya me voy','Elver Galarga','system','Analizar Problematica','Esteban Leal',to_date('30/11/07','DD/MM/RR'),'23:59',to_date('30/11/05','DD/MM/RR'),'19:58','22','Realizar sistema para Empresa de Trasnporte');
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('129','CRUD','CRUD','DML','DDL','php',to_date('23/10/16','DD/MM/RR'),'07:15',to_date('23/10/16','DD/MM/RR'),'15:30','10','laravel');
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('60','Cinepolis','Gonzo Murillo','Instalar nueva Red','Mantenimiento a equipo de computo','Gabriel Loba',to_date('31/12/16','DD/MM/RR'),'23:59',to_date('30/01/17','DD/MM/RR'),'20:58','2','jajaja');
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('61','Hotel Astor','probando','Mantenimiento al sistema','Actualizacion de Sistema','Gonzo huecorro',to_date('16/10/16','DD/MM/RR'),'00:58',to_date('30/12/16','DD/MM/RR'),'22:59','2','jijijiji');
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('64','Gran Tikal Futura','Elvin Porky','Mantenimiento al sistema','Mantenimiento Base de datos','Gabriel Loba',to_date('06/10/16','DD/MM/RR'),'23:59',to_date('31/12/16','DD/MM/RR'),'23:59','17','jojojo');
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('76','crud','crud','crud','crud','php',to_date('23/10/16','DD/MM/RR'),'07:15',to_date('23/10/16','DD/MM/RR'),'15:30','10','laravel');
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('57','Cinepolis','David Rojas','Actualizar el Developer Express','Mantenimiento Base de datos','Checha y su India maya',to_date('28/10/16','DD/MM/RR'),'09:08',to_date('31/10/16','DD/MM/RR'),'10:10','17','borrando el null');
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('102','probando---','probando----','probando','probando','probando',to_date('12/11/12','DD/MM/RR'),'01:12',to_date('12/11/12','DD/MM/RR'),'01:12','1','probando');
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('103','probando---','probando----','probando','probando','probando',to_date('12/11/12','DD/MM/RR'),'01:12',to_date('12/11/12','DD/MM/RR'),'01:12','1','probando');
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('110','probando---','probando----','probando','probando','probando',to_date('12/11/12','DD/MM/RR'),'01:12',to_date('12/11/12','DD/MM/RR'),'01:12','1','probando');
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('116','probando---','probando----','probando','probando','probando',to_date('12/11/12','DD/MM/RR'),'01:12',to_date('12/11/12','DD/MM/RR'),'01:12','1','probando');
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('111','probando---','probando----','probando','probando','probando',to_date('12/11/12','DD/MM/RR'),'01:12',to_date('12/11/12','DD/MM/RR'),'01:12','1','probando');
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('112','probando---','probando----','probando','probando','probando',to_date('12/11/12','DD/MM/RR'),'01:12',to_date('12/11/12','DD/MM/RR'),'01:12','1','probando');
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('113','probando---','probando----','probando','probando','probando',to_date('12/11/12','DD/MM/RR'),'01:12',to_date('12/11/12','DD/MM/RR'),'01:12','1','probando');
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('114','probando---','probando----','probando','probando','probando',to_date('12/11/12','DD/MM/RR'),'01:12',to_date('12/11/12','DD/MM/RR'),'01:12','1','probando');
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('115','probando---','probando----','probando','probando','probando',to_date('12/11/12','DD/MM/RR'),'01:12',to_date('12/11/12','DD/MM/RR'),'01:12','1','probando');
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('130','Centro Comercial La Trinidad','Gonzo Murillo','Instalar nueva Red','Instalar nueva Red','Gabriel Loba',to_date('31/12/15','DD/MM/RR'),'22:59',to_date('31/12/17','DD/MM/RR'),'22:59','2','prueba');
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('131','funciona','funcion','Instalar nueva Red','Instalar nueva Red','Gonzo huecorro',to_date('31/12/16','DD/MM/RR'),'23:59',to_date('31/12/17','DD/MM/RR'),'21:52','3','si funciona ');
Insert into PRUEBA.CONTROL_SERVICIO (ID,EMPRESA_CLIENTE,RESPONSABLE_EMPRESA_CLIENTE,PROYECTO,SERVICIO,ENCARGADO_PRESTAR_SERVICIO,FECHA_INICIO,HORA_INICIO,FECHA_FIN,HORA_FIN,DURACION_SERVICIO,DESCRIPCION) values ('132','ultimo','ultimo','Cambio Fibra Optica','Proyecto Timo ','Eduardo Barrios',to_date('31/12/15','DD/MM/RR'),'23:59',to_date('30/11/16','DD/MM/RR'),'21:58','15','FIBRA OPTICA');
REM INSERTING into PRUEBA.EMPRESAS_CLIENTE
SET DEFINE OFF;
Insert into PRUEBA.EMPRESAS_CLIENTE (ID,NOMBRE,DESCRIPCION,DIRECCION,PRESUPUESTO) values ('5','POLLO CAMPERO','RESTAURANTE','ZACAPA','20000');
Insert into PRUEBA.EMPRESAS_CLIENTE (ID,NOMBRE,DESCRIPCION,DIRECCION,PRESUPUESTO) values ('1','SAN JOSE','DISTRIBUIDOR DE PRODUCTOS DE AUTOS','GUATEMALA','12000');
Insert into PRUEBA.EMPRESAS_CLIENTE (ID,NOMBRE,DESCRIPCION,DIRECCION,PRESUPUESTO) values ('2','VRC','DISTRIBUIDOR DE MOTOCICLETAS','MAZATENANGO','5000');
Insert into PRUEBA.EMPRESAS_CLIENTE (ID,NOMBRE,DESCRIPCION,DIRECCION,PRESUPUESTO) values ('3','MASESA','VENTA DE MOTOCICLETAS','RETALHULEUJ','2000');
Insert into PRUEBA.EMPRESAS_CLIENTE (ID,NOMBRE,DESCRIPCION,DIRECCION,PRESUPUESTO) values ('4','ELEKTRA','VENTA DE ELECTRODOMESTICOS','COATEPEQUE','7000');
REM INSERTING into PRUEBA.EMPRESAS_CLIENTELA
SET DEFINE OFF;
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('2','Pollo Campero ','Restaurante','1ra avenida zona 2 Guatemala','Juan Perez');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('83','jiji','jiji','ji','jijoju');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('5','Centro Comercial La Trinidad','Centro Comercial','Zona 5 Retalhuleu','Gonzo Murillo');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('1','Checha ','12345','Reu','Tecnico de computadores 1');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('28','iiiii','iiiii','iii','iiii');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('61','Shadai','Internet','Reu','Tomy y Pichay');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('21','Cinepolis','Cine','Sacatepequez','Jhony Bravo');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('26','jajaja','jajaj','jaja','jaja');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('86','funciona','funcion','funciona','funcion');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('41','ultimo','ultimo','ultimo','ultimo');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('102','probando','pobando','probando','pobando');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('101','aaa','aaa','aaaa','aaa');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('121','Masesa','Tienda de motocicletas','La terminal de Mazatenango','David Rojas');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('122','Honda','Moto-repuestos','Tienda de repuestos para motocicletas','Micho rizo');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('123','Suzuki','Tienda de motocicletas y repuestos para motos','4ta calle 9-23 zona 1 Chiquimula','Benito Perez');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('124','Gran Karmel','Salon de eventos y Restaurante','San felipe Retalhuleu','Carlos Gonzales');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('125','IRTRA','Parque Recreativo','San Andres, Retalhuleu','Ricardo Orellana');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('126','Asazgua','Asociación de Azucareros de Guatemala','Zona 14 Edificio Europlaza Guatemala','Willy Calvillo');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('127','Ingenio el Pilar','Ingenio Azucarero','Cuyotenango Suchitepequez km 192','Ronald Gramajo');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('130','Claro','Empresa de telecomunicaciones','La Trinidad Coatepeque','Cesar Galvez');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('131','Tigo','Empresa de Telecomunicaciones competencia de Claro','La Trinidad Retalhulue','Efrain Calito');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('132','Transportes Mazariegos','Viajes a todo el pais','4ta avenida zona1 Retalhuleu','Oscar Mazariegos');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('133','Cengicaña','Laboratio de analisis de caña de azucar','km 405 Santa Lucía Cotzumalguapa','Marlo Mejía');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('134','Laboratorio Bioanalisis','Laboratorio clínico (examenes de todo tipo)','6ta calle 8-43 zona4 Morales Izabal','Ever Grajeda');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('135','Universidad UMG','Universidad de Guatemala','4 calle 5-32 zona 19 Guatemala','Francisco Meoño');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('136','Fundazucar','Empresa azucarera ','Santa Lucía Cotzumalguapa','Fernando Herrera');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('137','Despensa Familiar','Supermercado','Mazatenango','Mynor Avila');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('138','La torre','Supermercado','Quetzaltenango','Jorge Chavez');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('139','Comisariato Central','Supermercado','Coatepeque','Jony Alvares');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('140','El gran Gallo','Electrodomesticos','Santa Rosa Cuilapa','Debora CabezaParadas');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('141','Pollolandia','Restaurante','Avenida tulipanes, Izabal','Mario Castillo');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('142','Dell computers','venta de computadoras','USA','Mario Perez');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('143','Salvavidas','Agua Pura','San Carlos, Retalhuleu','Edmundo Grijalva');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('144','Monte Blanco','Deposito de Agua Pura','San Marcos','Alejandro Santamarina');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('145','Phonegap','Venta de Celulares','Mazatenango','Kasia Recinos');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('146','Alba Cinema','Cine','San Carlos, Huehuetenango','Pablo Rodas');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('147','html','html','html','html');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('148','css','css','css','css');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('149','javascript','javascript','javascript','javascript');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('150','php','php','php','php');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('151','asp','asp','asp','asp');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('152','c++','c++','c++','c++');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('153','java','java','java','java');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('154','sql','sql','sql','sql');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('155','pl','pl','pl','pl');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('156','perl','perl','perl','perl');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('157','xamarin','xamarin','xamarin','xamarin');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('158','delphi','delphi','delphi','delphi');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('159','Imprenta Lopez','impresion en volumenes grandes','Caracas','Alberto Barros');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('160','Cargo Exreso','Empresa de envios','San sebastian Retalhuleu','Miguel Abascal');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('161','Acer','Acer','Acer','Acer');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('162','Objetive C','Objetive C','Objetive C','Objetive C');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('163','Laravel','Laravel','Laravel','Laravel');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('164','Simphony','Simphony','Simphony','Simphony');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('165','Codenaither','Codenaither','Codenaither','Codenaither');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('166','Jquery','Jquery','Jquery','Jquery');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('167','Bootstrap','Bootstrap','Bootstrap','Bootstrap');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('168','Angular JS','Angular JS','Angular JS','Angular JS');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('169','Yii','Yii','Yii','Yii');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('170','Java EE','Java EE','Java EE','Java EE');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('171','Java SE','Java SE','Java SE','Java SE');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('172','google','google','google','google');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('173','facebook','red social','usa','Mark Zuckerberg');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('174','youtube','youtube','youtube','youtube');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('175','Coca cola','Coca cola','Coca cola','Coca cola');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('176','Apple','Electronica','usa','Steve Jobs');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('177','Amazon','Amazon','Amazon','Amazon');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('178','Nikon','Nikon','Nikon','Nikon');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('179','Puma','Puma','Puma','Puma');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('180','Nike','Nike','Nike','Nike');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('181','Adidas','Adidas','Adidas','Adidas');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('182','Mobil','Mobil','Mobil','Mobil');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('183','Pizza Hut','Pizza','España','Maria Fernanda');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('184','FedEx','FedEx','FedEx','FedEx');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('185','Colgate','Colgate','Colgate','Colgate');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('186','Mitsubishi','Mitsubishi','Mitsubishi','Mitsubishi');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('187','Old Navy','Old Navy','Old Navy','Old Navy');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('188','Texaco','Texaco','Texaco','Texaco');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('189','Taco Bell','Restaurante','Pradera Xela','Angel Mazariegos');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('190','Cerveza Gallo','Cerveceria','km65 honduras','Santos Curiel');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('191','Cerveceria Corona','Cerveceria','km43 Nicaragua','Steve Mcarney');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('192','Wall Mart','Wall Mart','Wall Mart','Wall Mart');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('193','Lipton','Lipton','Lipton','Lipton');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('194','Nintendo','Nintendo','Nintendo','Nintendo');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('195','Oral-B','Oral-B','Oral-B','Oral-B');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('196','Safeway','Safeway','Safeway','Safeway');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('197','Subway','Subway','Subway','Subway');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('198','Oreo','Galletas','Galletas','Oreo');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('199','red Lobster','Restaurante','China','China');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('200','Tic Tac','Relojeria','km53 Tegucigalpa, Honduras','Cristofer Cruzado');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('10','Pollo Pinulito','Comida Rapida','San sebastian Retalhuleu','Pepa la Cerdita PIG ');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('11','Hotel Astor','Comida Rapida','Coatepeque','Juan Camaney');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('222','25','55','55','55');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('13','Transportes Ya me voy','Transportes','Canal 46 Reu','Elver Galarga');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('25','Canal 46','Television','Reu','Ruben Barrios');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('23','Shimano','Bicicletas','Peten','Elsa Capuntas');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('24','a','b','c','d');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('85','validar','validar','validar','validar');
Insert into PRUEBA.EMPRESAS_CLIENTELA (ID,NOMBRE,DESCRIPCION,DIRECCION,RESPONSABLE) values ('225','ultimo','ultimo','ultimo','ultimo');
REM INSERTING into PRUEBA.FECHAS
SET DEFINE OFF;
Insert into PRUEBA.FECHAS (FECHA,HORA) values (to_date('06/06/16','DD/MM/RR'),'15:33');
Insert into PRUEBA.FECHAS (FECHA,HORA) values (to_date('31/10/16','DD/MM/RR'),'23:01');
REM INSERTING into PRUEBA.PERFIL_PUESTO_DE_TRABAJO
SET DEFINE OFF;
Insert into PRUEBA.PERFIL_PUESTO_DE_TRABAJO (ID,NOMBRE,DESCRIPCION,PUESTO_DE_TRABAJO) values ('1','Que aprenda rapido, autodidacta y eficiente','De 18 a 40 años','1');
REM INSERTING into PRUEBA.PROYECTO
SET DEFINE OFF;
Insert into PRUEBA.PROYECTO (ID,NOMBRE,DESCRIPCION) values ('14','mysql','mysql');
Insert into PRUEBA.PROYECTO (ID,NOMBRE,DESCRIPCION) values ('3','Cambio Fibra Optica','Hacer el cambio de la fibra');
Insert into PRUEBA.PROYECTO (ID,NOMBRE,DESCRIPCION) values ('4','Actualizar el Developer Express','Cambiar a Version de Developer Express .NET');
Insert into PRUEBA.PROYECTO (ID,NOMBRE,DESCRIPCION) values ('13','ejemplo','ejemplo');
Insert into PRUEBA.PROYECTO (ID,NOMBRE,DESCRIPCION) values ('1','Mantenimiento al sistema','Mantenimiento y requerimientos para actualizar el sistema');
Insert into PRUEBA.PROYECTO (ID,NOMBRE,DESCRIPCION) values ('2','Instalar nueva Red','Cablear red, agregar routers, switch, y repetidores');
Insert into PRUEBA.PROYECTO (ID,NOMBRE,DESCRIPCION) values ('5','system','system');
Insert into PRUEBA.PROYECTO (ID,NOMBRE,DESCRIPCION) values ('6','system','system');
Insert into PRUEBA.PROYECTO (ID,NOMBRE,DESCRIPCION) values ('7','dba','dba');
Insert into PRUEBA.PROYECTO (ID,NOMBRE,DESCRIPCION) values ('8','Proyecto DB','Proyecto DB');
Insert into PRUEBA.PROYECTO (ID,NOMBRE,DESCRIPCION) values ('9','Prueba Proyecto','Descripcion del Proyecto');
Insert into PRUEBA.PROYECTO (ID,NOMBRE,DESCRIPCION) values ('10','proyecto','descripcion');
Insert into PRUEBA.PROYECTO (ID,NOMBRE,DESCRIPCION) values ('11','project','project');
Insert into PRUEBA.PROYECTO (ID,NOMBRE,DESCRIPCION) values ('12','proyecto Vegeta','Tratar de Matar a Vegeta');
Insert into PRUEBA.PROYECTO (ID,NOMBRE,DESCRIPCION) values ('21','oracle','oracle');
REM INSERTING into PRUEBA.PUESTO_DE_TRABAJO
SET DEFINE OFF;
Insert into PRUEBA.PUESTO_DE_TRABAJO (ID,NOMBRE_PUESTO,DESCRIPCION) values ('1','Programador','Que domine tecnologias web');
Insert into PRUEBA.PUESTO_DE_TRABAJO (ID,NOMBRE_PUESTO,DESCRIPCION) values ('2','Auditor de sistemas','Que conozca metodologias auditoria de sistemas informaticos');
REM INSERTING into PRUEBA.SERVICIOS
SET DEFINE OFF;
Insert into PRUEBA.SERVICIOS (ID,NOMBRE,DESCRIPCION) values ('14','servicio','servicio');
Insert into PRUEBA.SERVICIOS (ID,NOMBRE,DESCRIPCION) values ('15','ingenieria','ingenieria');
Insert into PRUEBA.SERVICIOS (ID,NOMBRE,DESCRIPCION) values ('16','system','system');
Insert into PRUEBA.SERVICIOS (ID,NOMBRE,DESCRIPCION) values ('17','Login papaporky','Pedirle a su trabajador que descargue un login de internet para fingir que el hizo');
Insert into PRUEBA.SERVICIOS (ID,NOMBRE,DESCRIPCION) values ('5','Dar soporte a Clientes nuevos','Instruir y explicar el uso de las herramientas tecnologicas');
Insert into PRUEBA.SERVICIOS (ID,NOMBRE,DESCRIPCION) values ('6','Proyecto Timo ','Consiste en crear algo');
Insert into PRUEBA.SERVICIOS (ID,NOMBRE,DESCRIPCION) values ('9','Analizar Problematica','Crear Algoritmos para la resoluciÃ³n de Problemas que tiene un cliente');
Insert into PRUEBA.SERVICIOS (ID,NOMBRE,DESCRIPCION) values ('12','proyecto Vegeta','Tratar de Matar a Vegeta kame');
Insert into PRUEBA.SERVICIOS (ID,NOMBRE,DESCRIPCION) values ('1','Mantenimiento al sistema','Mantenimiento y actualizar el sistema');
Insert into PRUEBA.SERVICIOS (ID,NOMBRE,DESCRIPCION) values ('2','Instalar nueva Red','Cablear red, agregar routers, switch, y repetidores rj45');
Insert into PRUEBA.SERVICIOS (ID,NOMBRE,DESCRIPCION) values ('13','Prueba Programador sennior','Prueba Programador sennior');
Insert into PRUEBA.SERVICIOS (ID,NOMBRE,DESCRIPCION) values ('7','Servicio de Prueba','DescripciÃ³n de Prueba');
Insert into PRUEBA.SERVICIOS (ID,NOMBRE,DESCRIPCION) values ('10','Prueba 2','Prueba 2');
Insert into PRUEBA.SERVICIOS (ID,NOMBRE,DESCRIPCION) values ('11','Etapa de Prueba','Etapa de PRUEBA');
REM INSERTING into PRUEBA.TRABAJADORES
SET DEFINE OFF;
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('8','Emanuel Juarez','32452312','Coatepeque zona 3','Tecnico en reparación de Computadoras');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('9','Elmer del Cid','23435465','Colonia la Cañada Mazatenango','Administrador de Servidores');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('10','Abraham Laboriel','76875668','Almasillos Morales Izabal','Programador JR');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('11','Carlos Velasquez','87964536','Colonia la Trinidad Guatemala','DBA');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('12','Enrique Perez','65465719','Pensilvania','Conserje');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('13','Esteban Marroquín','87674930','Tierra Colorada El palmar Quetzaltenango','Desarrollador Android');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('14','Estiven Macarnety','53460997','Santa Lucía cotzumalguapa','Programador JR');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('15','Rafael Hernandez','76544432','Zona 14 Guatemala','Php Sennior');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('16','Nelson Gonzales','76483940','Zona 3 Escuintla','Desarrollador .NET');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('17','Jorge Mario Rivera','6547382','Zona 6 Guatemala','T&eacute;cnico en Redes');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('21','Julio Garcia','54365434','Escuintla','Administrador de Sistemas');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('19','Carlos el Pescado Ruiz','57483920','USA','Delantero');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('20','Angel Mazariegos','76859467','Colonia el Pedregal 5-65 San Marcos','LameBolas');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('22','Raymundo Grijalva','65789009','Tiquisate','Reparador de computadoras');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('23','Isaias Benavente','11223344','Suchitepequez','Aguador');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('24','Henry Gonzales','33445566','Coatepeque','Desarrollador JAVA');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('25','Luis Estuardo Morales','32435465','Sanarate','Desarrollador PHP / LARAVEL');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('26','Angel Marquez','44443333','Peten','Programador JR');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('27','Dennis Ortiz','56432345','Zacapa','Auditor de Sistemas');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('28','Gustavo Letona','56789009','Jalapa','Analista programador');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('29','Eddy Fortin','0','Cuilapa Santa Rosa','Vendedor');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('30','Mario Castillo','99999999','Jutiapa','Tecnico en computadoras');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('31','Jorge Lopez','99943432','San Benito Peten','Tecnico en electrónica');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('32','William Rolnado Avila','11122233','Santa Catarina Ixtahuacan','Ninja JAVA');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('33','Donald Trump','33224455','San Luis Retalhulue','SQL server Master');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('34','Barack Obama','32435465','San Antonio Suchitepequez','Tecnico en computadoras');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('35','George Us','12345678','San Bernardino Suchitepequez','DBA');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('36','Estiven Sigal','34213234','Ayutla San Marcos','Programador JR');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('37','Jhony Grijalva','87786556','Teculután','Programadro Web');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('38','Julio Cesar Wanchope','44567841','El Progreso','Diseñador Web');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('39','Zinadine zidane','32453357','Livingston Izabal','Desarrollador Javascript');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('40','Eliazar Maldonado','55776829','San Marcos','Tecnico en computadoras');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('41','Melvin Valladares','12321234','San Lucas Sacatepequez','Programador Sennior');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('42','Juan Francisco Roche','43542312','Guatemala zona 6','Desarrollador Angular.js');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('44','Rodrigo Giron','13243546','Momostenango','Desarrollador Node.js');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('45','Javier Gonzales','34567899','Totonicapan','Html Sennior');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('46','Fredy Antonio Custorio Reyes','9876543','Retalhuleu','Oracle Experto');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('61','messi','1234566778','argentina','pajiador');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('1','Checha ','12345','Reu','Tecnico de computadores');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('2','Gabriel Loba','55555','Mazatenango','Programador');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('3','Gonzo huecorro','33333','Mas alla','Aguador');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('4','Esteban Leal','41793176','4ta Calle 9-42 zona 1 Retalhuleu','Programador Sennior Jr');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('5','Eduardo Barrios','54441004','4ta Calle 9-42 zona 1 Retalhuleu , Guatemala ','Programador JR ');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('6','Eduardo Barrios','54441004','4ta Calle 9-42 zona 1 Retalhuleu','Programador Sennior');
Insert into PRUEBA.TRABAJADORES (ID,NOMBRE,TELEFONO,DIRECCION,PUESTO) values ('7','Alexander Leal','54674323','Quetzaltenango, terminal vieja','Administrador de Base de Datos');
REM INSERTING into PRUEBA.USUARIOS
SET DEFINE OFF;
Insert into PRUEBA.USUARIOS (ID,NOMBRE,APELLIDO) values ('21','system123','root');
Insert into PRUEBA.USUARIOS (ID,NOMBRE,APELLIDO) values ('24','Mambo','Agustin123');
Insert into PRUEBA.USUARIOS (ID,NOMBRE,APELLIDO) values ('26','Jorge','mysql');
Insert into PRUEBA.USUARIOS (ID,NOMBRE,APELLIDO) values ('27','sysDBA','Oracle');
Insert into PRUEBA.USUARIOS (ID,NOMBRE,APELLIDO) values ('28','Eduardo','Barrios');
Insert into PRUEBA.USUARIOS (ID,NOMBRE,APELLIDO) values ('29','Juancho','Gonzales');
REM INSERTING into PRUEBA.USUARIOS_SISTEMA
SET DEFINE OFF;
Insert into PRUEBA.USUARIOS_SISTEMA (ID,NOMBRE,PASSWORD,TIPO_USUARIO,TIPO_USUARIO_NUM,ESTADO) values ('3','system','root','admin','1','1');
Insert into PRUEBA.USUARIOS_SISTEMA (ID,NOMBRE,PASSWORD,TIPO_USUARIO,TIPO_USUARIO_NUM,ESTADO) values ('4','Eduardo','Barrios','admin','1','0');
Insert into PRUEBA.USUARIOS_SISTEMA (ID,NOMBRE,PASSWORD,TIPO_USUARIO,TIPO_USUARIO_NUM,ESTADO) values ('5','php','.net','user','0','1');
Insert into PRUEBA.USUARIOS_SISTEMA (ID,NOMBRE,PASSWORD,TIPO_USUARIO,TIPO_USUARIO_NUM,ESTADO) values ('6','super','super','user','0','0');
Insert into PRUEBA.USUARIOS_SISTEMA (ID,NOMBRE,PASSWORD,TIPO_USUARIO,TIPO_USUARIO_NUM,ESTADO) values ('7','Rony','rodriguez123','admin','1','1');
Insert into PRUEBA.USUARIOS_SISTEMA (ID,NOMBRE,PASSWORD,TIPO_USUARIO,TIPO_USUARIO_NUM,ESTADO) values ('8','Elmer','churampi123','admin','1','1');
Insert into PRUEBA.USUARIOS_SISTEMA (ID,NOMBRE,PASSWORD,TIPO_USUARIO,TIPO_USUARIO_NUM,ESTADO) values ('9','Angel','Rivera%$#','user','0','0');
Insert into PRUEBA.USUARIOS_SISTEMA (ID,NOMBRE,PASSWORD,TIPO_USUARIO,TIPO_USUARIO_NUM,ESTADO) values ('10','Fernando','Grijalva543','user','0','0');
Insert into PRUEBA.USUARIOS_SISTEMA (ID,NOMBRE,PASSWORD,TIPO_USUARIO,TIPO_USUARIO_NUM,ESTADO) values ('11','Mario ','Perez$""#','user','0','0');
Insert into PRUEBA.USUARIOS_SISTEMA (ID,NOMBRE,PASSWORD,TIPO_USUARIO,TIPO_USUARIO_NUM,ESTADO) values ('12','Chapulin','Colorado','user','0','0');
Insert into PRUEBA.USUARIOS_SISTEMA (ID,NOMBRE,PASSWORD,TIPO_USUARIO,TIPO_USUARIO_NUM,ESTADO) values ('13','Drangon_ball','Z1234','user','0','0');
Insert into PRUEBA.USUARIOS_SISTEMA (ID,NOMBRE,PASSWORD,TIPO_USUARIO,TIPO_USUARIO_NUM,ESTADO) values ('14','asp','.net','user','0','1');
Insert into PRUEBA.USUARIOS_SISTEMA (ID,NOMBRE,PASSWORD,TIPO_USUARIO,TIPO_USUARIO_NUM,ESTADO) values ('15','visaul','studia15','user','0','1');
Insert into PRUEBA.USUARIOS_SISTEMA (ID,NOMBRE,PASSWORD,TIPO_USUARIO,TIPO_USUARIO_NUM,ESTADO) values ('16','Acer','123','admin','1','1');
Insert into PRUEBA.USUARIOS_SISTEMA (ID,NOMBRE,PASSWORD,TIPO_USUARIO,TIPO_USUARIO_NUM,ESTADO) values ('17','a','b','admin','1','1');
Insert into PRUEBA.USUARIOS_SISTEMA (ID,NOMBRE,PASSWORD,TIPO_USUARIO,TIPO_USUARIO_NUM,ESTADO) values ('18','adsf','aasdf','user','0','0');
Insert into PRUEBA.USUARIOS_SISTEMA (ID,NOMBRE,PASSWORD,TIPO_USUARIO,TIPO_USUARIO_NUM,ESTADO) values ('1','admin','root','admin','1','1');
Insert into PRUEBA.USUARIOS_SISTEMA (ID,NOMBRE,PASSWORD,TIPO_USUARIO,TIPO_USUARIO_NUM,ESTADO) values ('2','user','pdo','admin','1','0');
Insert into PRUEBA.USUARIOS_SISTEMA (ID,NOMBRE,PASSWORD,TIPO_USUARIO,TIPO_USUARIO_NUM,ESTADO) values ('19','ALL','ALL','user','0','1');
--------------------------------------------------------
--  DDL for Index EMPRESAS_CLIENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBA"."EMPRESAS_CLIENTE_PK" ON "PRUEBA"."EMPRESAS_CLIENTE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SERVICIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBA"."SERVICIOS_PK" ON "PRUEBA"."SERVICIOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ID_PKCLIENTES
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBA"."ID_PKCLIENTES" ON "PRUEBA"."CLIENTES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CONTROL_SERVICIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBA"."CONTROL_SERVICIO_PK" ON "PRUEBA"."CONTROL_SERVICIO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USUARIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBA"."USUARIOS_PK" ON "PRUEBA"."USUARIOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USUARIOS_SISTEMA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBA"."USUARIOS_SISTEMA_PK" ON "PRUEBA"."USUARIOS_SISTEMA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EMPRESAS_CLIENTELA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBA"."EMPRESAS_CLIENTELA_PK" ON "PRUEBA"."EMPRESAS_CLIENTELA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PROYECTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBA"."PROYECTO_PK" ON "PRUEBA"."PROYECTO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBA"."ID_PK" ON "PRUEBA"."PUESTO_DE_TRABAJO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRABAJADORES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBA"."TRABAJADORES_PK" ON "PRUEBA"."TRABAJADORES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ID_PERFILPUESTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBA"."ID_PERFILPUESTO_PK" ON "PRUEBA"."PERFIL_PUESTO_DE_TRABAJO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SERVICIOS
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."SERVICIOS" ADD CONSTRAINT "SERVICIOS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRUEBA"."SERVICIOS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPRESAS_CLIENTE
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."EMPRESAS_CLIENTE" ADD CONSTRAINT "EMPRESAS_CLIENTE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRUEBA"."EMPRESAS_CLIENTE" MODIFY ("PRESUPUESTO" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."EMPRESAS_CLIENTE" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."EMPRESAS_CLIENTE" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."EMPRESAS_CLIENTE" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."EMPRESAS_CLIENTE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PUESTO_DE_TRABAJO
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."PUESTO_DE_TRABAJO" ADD CONSTRAINT "ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRUEBA"."PUESTO_DE_TRABAJO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROYECTO
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."PROYECTO" ADD CONSTRAINT "PROYECTO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRUEBA"."PROYECTO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."USUARIOS" ADD CONSTRAINT "USUARIOS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRUEBA"."USUARIOS" MODIFY ("APELLIDO" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."USUARIOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."USUARIOS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERFIL_PUESTO_DE_TRABAJO
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."PERFIL_PUESTO_DE_TRABAJO" ADD CONSTRAINT "ID_PERFILPUESTO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRUEBA"."PERFIL_PUESTO_DE_TRABAJO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIOS_SISTEMA
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."USUARIOS_SISTEMA" ADD CONSTRAINT "USUARIOS_SISTEMA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRUEBA"."USUARIOS_SISTEMA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRABAJADORES
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."TRABAJADORES" ADD CONSTRAINT "TRABAJADORES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRUEBA"."TRABAJADORES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONTROL_SERVICIO
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."CONTROL_SERVICIO" ADD CONSTRAINT "CONTROL_SERVICIO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRUEBA"."CONTROL_SERVICIO" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."CONTROL_SERVICIO" MODIFY ("DURACION_SERVICIO" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."CONTROL_SERVICIO" MODIFY ("HORA_FIN" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."CONTROL_SERVICIO" MODIFY ("FECHA_FIN" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."CONTROL_SERVICIO" MODIFY ("HORA_INICIO" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."CONTROL_SERVICIO" MODIFY ("FECHA_INICIO" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."CONTROL_SERVICIO" MODIFY ("ENCARGADO_PRESTAR_SERVICIO" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."CONTROL_SERVICIO" MODIFY ("SERVICIO" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."CONTROL_SERVICIO" MODIFY ("PROYECTO" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."CONTROL_SERVICIO" MODIFY ("RESPONSABLE_EMPRESA_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."CONTROL_SERVICIO" MODIFY ("EMPRESA_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."CONTROL_SERVICIO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPRESAS_CLIENTELA
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."EMPRESAS_CLIENTELA" ADD CONSTRAINT "EMPRESAS_CLIENTELA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRUEBA"."EMPRESAS_CLIENTELA" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."EMPRESAS_CLIENTELA" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."EMPRESAS_CLIENTELA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."EMPRESAS_CLIENTELA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENTES
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."CLIENTES" ADD CONSTRAINT "ID_PKCLIENTES" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRUEBA"."CLIENTES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PERFIL_PUESTO_DE_TRABAJO
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."PERFIL_PUESTO_DE_TRABAJO" ADD CONSTRAINT "ID_PUESTO_FK" FOREIGN KEY ("PUESTO_DE_TRABAJO")
	  REFERENCES "PRUEBA"."PUESTO_DE_TRABAJO" ("ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger CLIENTES_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PRUEBA"."CLIENTES_TRG" 
BEFORE INSERT ON CLIENTES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT CLIENTES_SEQ1.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PRUEBA"."CLIENTES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CONTROL_SERVICIO_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PRUEBA"."CONTROL_SERVICIO_TRG" 
BEFORE INSERT ON CONTROL_SERVICIO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.DESCRIPCION IS NULL THEN
      SELECT CONTROL_SERVICIO_SEQ.NEXTVAL INTO :NEW.DESCRIPCION FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PRUEBA"."CONTROL_SERVICIO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CONTROL_SERVICIO_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PRUEBA"."CONTROL_SERVICIO_TRG1" 
BEFORE INSERT ON CONTROL_SERVICIO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT CONTROL_SERVICIO_SEQ1.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PRUEBA"."CONTROL_SERVICIO_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CONTROL_SERVICIO_TRG2
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PRUEBA"."CONTROL_SERVICIO_TRG2" 
BEFORE INSERT ON CONTROL_SERVICIO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.HORA_FIN IS NULL THEN
      SELECT CONTROL_SERVICIO_SEQ2.NEXTVAL INTO :NEW.HORA_FIN FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PRUEBA"."CONTROL_SERVICIO_TRG2" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EMPRESAS_CLIENTELA_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PRUEBA"."EMPRESAS_CLIENTELA_TRG" 
BEFORE INSERT ON EMPRESAS_CLIENTELA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PRUEBA"."EMPRESAS_CLIENTELA_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EMPRESAS_CLIENTELA_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PRUEBA"."EMPRESAS_CLIENTELA_TRG1" 
BEFORE INSERT ON EMPRESAS_CLIENTELA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT EMPRESAS_CLIENTELA_SEQ1.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PRUEBA"."EMPRESAS_CLIENTELA_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EMPRESAS_CLIENTE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PRUEBA"."EMPRESAS_CLIENTE_TRG" 
BEFORE INSERT ON EMPRESAS_CLIENTE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT EMPRESAS_CLIENTE_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PRUEBA"."EMPRESAS_CLIENTE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PROYECTO_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PRUEBA"."PROYECTO_TRG" 
BEFORE INSERT ON PROYECTO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.DESCRIPCION IS NULL THEN
      SELECT PROYECTO_SEQ.NEXTVAL INTO :NEW.DESCRIPCION FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PRUEBA"."PROYECTO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PROYECTO_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PRUEBA"."PROYECTO_TRG1" 
BEFORE INSERT ON PROYECTO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT PROYECTO_SEQ1.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PRUEBA"."PROYECTO_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SERVICIOS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PRUEBA"."SERVICIOS_TRG" 
BEFORE INSERT ON SERVICIOS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.DESCRIPCION IS NULL THEN
      SELECT SERVICIOS_SEQ.NEXTVAL INTO :NEW.DESCRIPCION FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PRUEBA"."SERVICIOS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SERVICIOS_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PRUEBA"."SERVICIOS_TRG1" 
BEFORE INSERT ON SERVICIOS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT SERVICIOS_SEQ1.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PRUEBA"."SERVICIOS_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRABAJADORES_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PRUEBA"."TRABAJADORES_TRG" 
BEFORE INSERT ON TRABAJADORES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT TRABAJADORES_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PRUEBA"."TRABAJADORES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USUARIOS_SISTEMA_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PRUEBA"."USUARIOS_SISTEMA_TRG" 
BEFORE INSERT ON USUARIOS_SISTEMA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PRUEBA"."USUARIOS_SISTEMA_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USUARIOS_SISTEMA_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PRUEBA"."USUARIOS_SISTEMA_TRG1" 
BEFORE INSERT ON USUARIOS_SISTEMA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PRUEBA"."USUARIOS_SISTEMA_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USUARIOS_SISTEMA_TRG2
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PRUEBA"."USUARIOS_SISTEMA_TRG2" 
BEFORE INSERT ON USUARIOS_SISTEMA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT USUARIOS_SISTEMA_SEQ2.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PRUEBA"."USUARIOS_SISTEMA_TRG2" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USUARIOS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PRUEBA"."USUARIOS_TRG" 
BEFORE INSERT ON USUARIOS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT USUARIOS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PRUEBA"."USUARIOS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Function CUSTOM_AUTH
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "PRUEBA"."CUSTOM_AUTH" (p_username in VARCHAR2, p_password in VARCHAR2)
return BOOLEAN
is
  l_password varchar2(4000);
  l_stored_password varchar2(4000);
  l_expires_on date;
  l_count number;
begin
-- First, check to see if the user is in the user table
select count(*) into l_count from demo_users where user_name = p_username;
if l_count > 0 then
  -- First, we fetch the stored hashed password & expire date
  select password, expires_on into l_stored_password, l_expires_on
   from demo_users where user_name = p_username;

  -- Next, we check to see if the user's account is expired
  -- If it is, return FALSE
  if l_expires_on > sysdate or l_expires_on is null then

    -- If the account is not expired, we have to apply the custom hash
    -- function to the password
    l_password := custom_hash(p_username, p_password);

    -- Finally, we compare them to see if they are the same and return
    -- either TRUE or FALSE
    if l_password = l_stored_password then
      return true;
    else
      return false;
    end if;
  else
    return false;
  end if;
else
  -- The username provided is not in the DEMO_USERS table
  return false;
end if;
end;

/
--------------------------------------------------------
--  DDL for Function CUSTOM_HASH
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "PRUEBA"."CUSTOM_HASH" (p_username in varchar2, p_password in varchar2)
return varchar2
is
  l_password varchar2(4000);
  l_salt varchar2(4000) := 'G9J2M9BAD1HA07BS1K2XADORMFCCDZ';
begin

-- This function should be wrapped, as the hash algorhythm is exposed here.
-- You can change the value of l_salt or the method of which to call the
-- DBMS_OBFUSCATOIN toolkit, but you much reset all of your passwords
-- if you choose to do this.

l_password := utl_raw.cast_to_raw(dbms_obfuscation_toolkit.md5
  (input_string => p_password || substr(l_salt,10,13) || p_username ||
    substr(l_salt, 4,10)));
return l_password;
end;

/
